addpath matlab;
% compile with GPU
% vl_compilenn(   'enableGpu', true, ...
%                 'cudaMethod', 'nvcc', ...
%                 'cudaRoot', '/usr/local/cuda-6.5', ...
%                 'enableCudnn', true, ...
%                 'cudnnRoot', '/u/eems/workspace1/yhchen/tools/cudnn-v2' ...
%             );
% compile with CPU only        
vl_compilenn(   'enableGpu', false, ...
                'enableCudnn', false ...
            );
                