addpath matlab;
vl_compilenn(   'enableGpu', true, ...
                'cudaMethod', 'nvcc', ...
                'cudaRoot', '/usr/local/cuda-6.5', ...
                'enableCudnn', true, ...
                'cudnnRoot', '/u/eems/workspace1/yhchen/tools/cudnn-v2' ...
            );